server.servlet.context-path=/portal
vectis.path=/ops
spring.datasource.url=${VECTIS_CONSUMER_DB:jdbc:h2:file:./target/consumer-state}
spring.datasource.username=${VECTIS_TEST_DB_USER:sa}
spring.datasource.password=${VECTIS_TEST_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${VECTIS_CONSUMER_DDL:update}
spring.jpa.open-in-view=false
